#!application-dev.yml 开发环境配置文件
server:
  port: 8090 #端口
debug: false #调试模式
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true #显示sql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #驱动类
    url: jdbc:mysql://localhost:3306/hrms?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&connectTimeout=0&serverTimezone=UTC
    username: root #数据库用户名
    password: kingston #密码
  thymeleaf:
    cache: false #缓存
    mode: HTML
  mvc:
    favicon:
      enabled: false
  output:
    ansi:
      enabled: detect #控制台多彩输出
logging:
  level: debug
  level.top: debug
  file: C:/Users/Ning/Desktop/upload/log.log
cas:
  server:
    host:
      url: http://login.greathiit.com  #CAS服务地址
      login_url: ${cas.server.host.url}/login  #CAS服务登录地址
      logout_url: ${cas.server.host.url}/logout?service=${app.server.host.url} #CAS服务登出地址
app:
  server:
    host:
      url: http://localhost:8090 #应用访问地址
  login:
    url: /login  #应用登录地址
  logout:
    url: /logout #应用登出地址
  admin:
    accounts: thinkgem,13945058053 #配置管理员账户,每个账户用逗号(,)分隔